spring:
  application:
    name: kinect-config-app
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: config-db
  cloud:
    config:
      enabled: false
#server:
#  port: 8081
app:
  client:
    mjml:
      url: "http://localhost:3000/mjml2html"
      api-key: ${AZURE_APIM_KEY}