#server:
#  port: 8082
app:
  feature-flag:
    send-email: true
  client:
    template:
      url: https://dev-kinect-apim-service.azure-api.net/config/v1/kinect/messaging/config/template/personalize
      apiKey: ${AZURE_APIM_KEY}
  email:
    azure:
      connectionString: ${AZURE_EMAIL_CONNECTION}
      defaults:
        senderAddress: DoNotReply@kinectmessaging.com
spring:
  cloud:
    config:
      enabled: false
#logging:
#  level:
#    reactor:
#      netty:
#        http:
#          client: DEBUG