spring:
  data:
    mongodb:
      uri: ${AZURE_COSMOS_MONGO_CONNECTION_STRING}
      database: ${AZURE_COSMOS_MONGO_DATABASE}
app:
  endpoint:
    mjml:
      url: "https://dev-kinect-apim-service.azure-api.net/mjml/v1/mjml2html"
      api-key: ${AZURE_APIM_KEY}
