name: Kinect Messaging Deployment
on:
  push:
    branches: [ none ]
    paths:
      - 'none'
  workflow_dispatch:

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: maven build, clean
        run: |
          mvn -B clean package -DskipTests

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Action to deploy to dev with main branch
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az spring app deploy \
            --resource-group dev-apps-rg \
            --service dev-kinect-spring-services \
            --name kinect-config \
            --artifact-path ${{ env.ASC_PACKAGE_PATH }}/apps/config/**/*.jar \
            --runtime-version Java_17 \

#      - name: deploy to production with artifact
#        uses: azure/spring-apps-deploy@v1
#        with:
#          azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
#          action: Deploy
#          service-name: dev-kinect-spring-services
#          app-name: kinect-config
#          use-staging-deployment: false
#          package: ${{ env.ASC_PACKAGE_PATH }}/apps/config/target/*.jar
#          deployment-name: default
#          runtime-version: Java_17
#          create-new-deployment: true
#          language-framework: Spring Boot
